# Packaging Options

if(CPACK_PACKAGE_FILE_NAME STREQUAL "${CPACK_SOURCE_PACKAGE_FILE_NAME}")
	set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY ON)
endif()

if(CPACK_GENERATOR MATCHES "NSIS")
	set(CPACK_PACKAGE_FILE_NAME "${CPACK_NSIS_FILE_NAME}")
endif()

if(DEFINED CPACK_RPM_PACKAGE_SOURCES AND CPACK_RPM_PACKAGE_SOURCES)
	set(CPACK_RPM_PACKAGE_NAME "${CPACK_RPM_PACKAGE_SOURCE}")
endif()
